# Generated by Django 5.1.3 on 2024-11-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_carrinho_item_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_carrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item_carrinho',
            name='perfil_carrinho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item_carrinho', to='perfil.perfil'),
        ),
    ]
