# Generated by Django 5.1.7 on 2025-03-20 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='is_admin',
        ),
    ]
