# Generated by Django 5.1.7 on 2025-03-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_perfil_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
