# Generated by Django 5.1.3 on 2024-12-02 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_item_carrinho_preco_and_more'),
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_carrinho',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.CreateModel(
            name='Lista_Desejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupas.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_desejos', to='perfil.perfil')),
            ],
        ),
    ]
