# Generated by Django 5.1.3 on 2024-12-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_item_carrinho_imagem_lista_desejos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_carrinho',
            name='imagem',
        ),
    ]
