# Generated by Django 5.1.3 on 2024-12-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_remove_item_carrinho_imagem'),
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_desejos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupas.produto', unique=True),
        ),
    ]
