# Generated by Django 5.1.3 on 2024-12-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_lista_desejos_produto'),
        ('roupas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_desejos',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupas.produto'),
        ),
        migrations.AddConstraint(
            model_name='lista_desejos',
            constraint=models.UniqueConstraint(fields=('usuario', 'produto'), name='unique_usuario_produto'),
        ),
    ]
