# Generated by Django 5.1.3 on 2025-03-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_pedido_itempedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_carrinho',
            old_name='perfil_carrinho',
            new_name='usuario',
        ),
    ]
